name: libretranslate
region: fra
domains:
  - domain: translate.verteco.app
    type: PRIMARY
services:
  - name: libretranslate-app
    github:
      branch: main
      deploy_on_push: true
      repo: verteco/LibreTranslate
    build_command: ./venv/bin/python scripts/compile_locales.py
    dockerfile_path: Dockerfile
    http_port: 5000
    instance_size_slug: professional-xs
    instance_count: 1
    autoscaling:
      min_instances: 1
      max_instances: 5
      cpu_threshold: 75
    routes:
      - path: /
    envs:
      - key: LT_API_KEYS
        value: "true"
      - key: LT_SKIP_INSTALL_MODELS
        value: "true"
      - key: LT_LOAD_ONLY
        value: "en,de,fr,it,es"
      - key: LT_MEMORY_REDUCTION
        value: "true"
      - key: LT_HOST
        value: "0.0.0.0"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: HEALTH_CHECK_PATH
        value: "/languages"
    health_check:
      http_path: /languages
      initial_delay_seconds: 120
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 10
