name: libretranslate
region: fra
domains:
  - domain: translate.verteco.app
    type: PRIMARY
services:
  - name: libretranslate-app
    github:
      branch: main
      deploy_on_push: true
      repo: verteco/LibreTranslate
    build_command: ./venv/bin/python scripts/compile_locales.py
    dockerfile_path: docker/Dockerfile.do
    http_port: 5000
    instance_size_slug: professional-xs
    instance_count: 1
    autoscaling:
      min_instances: 1
      max_instances: 5
      cpu_threshold: 75
    routes:
      - path: /
    envs:
      - key: LT_API_KEYS
        value: "true"
      - key: LT_LOAD_ONLY
        value: "en"
      - key: LT_MEMORY_REDUCTION
        value: "true"
