name: libretranslate
region: fra
services:
  - name: libretranslate-app
    github:
      branch: main
      deploy_on_push: true
      repo: verteco/LibreTranslate
    build_command: ./venv/bin/python scripts/compile_locales.py
    dockerfile_path: docker/Dockerfile.do
    http_port: 5000
    instance_count: 1
    instance_size_slug: basic-s
    routes:
      - path: /
    envs:
      - key: LT_API_KEYS
        value: "true"
      - key: LT_LOAD_ONLY
        value: "en"
      - key: LT_MEMORY_REDUCTION
        value: "true"
